[package]
name = "extralife"
version = "0.1.0"
edition = "2021"
parallel-compiler = true

[dependencies]
#sysinfo = "0.31.3"
sysinfo = "0.30.13"

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"